USE DemoDb;
GO
SET NOCOUNT ON;
DROP TABLE IF EXISTS dbo.FO_110;
DROP TABLE IF EXISTS dbo.FO_140;
GO
ALTER DATABASE WideWorldImportersDW SET COMPATIBILITY_LEVEL = 110
GO
GO
-- TURN ON QUERY PLAN
SELECT * INTO dbo.FO_110 FROM WideWorldImportersDW.Fact.[Order];

ALTER DATABASE WideWorldImportersDW SET COMPATIBILITY_LEVEL = 140
GO
SELECT * INTO dbo.FO_140 FROM WideWorldImportersDW.Fact.[Order];

GO
